version: '3.8'

services:
  evolution:
    image: evoapicloud/evolution-api:latest
    container_name: evolution_api
    environment:
      EVOLUTION_API_PORT: 8080
      EVOLUTION_API_HOST: 0.0.0.0
      EVOLUTION_DATABASE_ENABLED: "false"
      EVOLUTION_STORE_TYPE: json
    ports:
      - "8080:8080"
    volumes:
      - evolution_data:/evolution/store
    restart: unless-stopped

volumes:
  evolution_data:
